// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentManager.Data;

#nullable disable

namespace TournamentManager.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260106192636_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournamentManager.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("int");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TitulosGanados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Team BDS",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "BDS",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 2,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "G2 Stride",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "G2",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 3,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Karmine Corp",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "KARM",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 4,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Team Falcons",
                            Pais = "MENA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "FAL",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 5,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "FURIA Esports",
                            Pais = "BR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "FUR",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 6,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Oxygen Esports",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "OXG",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 7,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Gentle Mates Alpine",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "GMA",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 8,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Spacestation Gaming",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "SSG",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 9,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "NRG Esports",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "NRG",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 10,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Geekay Esports",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "GKAY",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 11,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "The Ultimates",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "ULT",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 12,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Wildcard",
                            Pais = "OCE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "WC",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 13,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Ninjas in Pyjamas",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "NIP",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 14,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Team Vitality",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "VIT",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 15,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Team Secret",
                            Pais = "SAM",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "SECR",
                            TitulosGanados = 0
                        },
                        new
                        {
                            Id = 16,
                            GolesAFavor = 0,
                            GolesEnContra = 0,
                            Nombre = "Gen.G Mobil1 Racing",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            Tag = "GENG",
                            TitulosGanados = 0
                        });
                });

            modelBuilder.Entity("TournamentManager.Models.EquipoPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EquipoPartidos");
                });

            modelBuilder.Entity("TournamentManager.Models.EquipoTorneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("PosicionFinal")
                        .HasColumnType("int");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("EquipoTorneos");
                });

            modelBuilder.Entity("TournamentManager.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsistenciasTotales")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("GolesTotales")
                        .HasColumnType("int");

                    b.Property<int>("MVPsTotales")
                        .HasColumnType("int");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("SalvadasTotales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 1,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "M0nkeyM00n",
                            Nombre = "Evan \"M0nkey M00n\" Rogez",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 2,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 1,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "ExoTiiK",
                            Nombre = "Brice \"ExoTiiK\" Bigeard",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 3,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 1,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "zen",
                            Nombre = "Alexis \"zen\" Bernier",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 4,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 2,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Atomic",
                            Nombre = "Atomic",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 5,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 2,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "BeastMode",
                            Nombre = "Landon \"BeastMode\" Konerman",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 6,
                            AsistenciasTotales = 0,
                            Edad = 20,
                            EquipoId = 2,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Daniel",
                            Nombre = "Daniel",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 7,
                            AsistenciasTotales = 0,
                            Edad = 25,
                            EquipoId = 3,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Vatira",
                            Nombre = "Vatira",
                            Pais = "BE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 8,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 3,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Atow",
                            Nombre = "Atow",
                            Pais = "BE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 9,
                            AsistenciasTotales = 0,
                            Edad = 21,
                            EquipoId = 3,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "dralii",
                            Nombre = "dralii",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 10,
                            AsistenciasTotales = 0,
                            Edad = 20,
                            EquipoId = 4,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Trk511",
                            Nombre = "Trk511",
                            Pais = "SA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 11,
                            AsistenciasTotales = 0,
                            Edad = 21,
                            EquipoId = 4,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Rw9",
                            Nombre = "Rw9",
                            Pais = "SA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 12,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 4,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Kiileerrz",
                            Nombre = "Kiileerrz",
                            Pais = "SA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 13,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 5,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "yANXNZ",
                            Nombre = "yANXNZ",
                            Pais = "BR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 14,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 5,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Lostt",
                            Nombre = "Lostt",
                            Pais = "BR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 15,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 5,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "DRUFINHO",
                            Nombre = "DRUFINHO",
                            Pais = "BR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 16,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 6,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "OXG_A",
                            Nombre = "PlayerA_OXG",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 17,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 6,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "OXG_B",
                            Nombre = "PlayerB_OXG",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 18,
                            AsistenciasTotales = 0,
                            Edad = 21,
                            EquipoId = 6,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "OXG_C",
                            Nombre = "PlayerC_OXG",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 19,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 7,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Juicy",
                            Nombre = "Juicy",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 20,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 7,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Yujin",
                            Nombre = "Yujin",
                            Pais = "KR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 21,
                            AsistenciasTotales = 0,
                            Edad = 21,
                            EquipoId = 7,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Seikoo",
                            Nombre = "Seikoo",
                            Pais = "FR",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 22,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 8,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Scrzbbles",
                            Nombre = "Scrzbbles",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 23,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 8,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "reveal",
                            Nombre = "reveal",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 24,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 8,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "kofyr",
                            Nombre = "kofyr",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 25,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 9,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Atomic",
                            Nombre = "Atomic",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 26,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 9,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "BeastMode",
                            Nombre = "BeastMode",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 27,
                            AsistenciasTotales = 0,
                            Edad = 20,
                            EquipoId = 9,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Daniel",
                            Nombre = "Daniel",
                            Pais = "USA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 28,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 10,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Archie",
                            Nombre = "Archie",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 29,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 10,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Joyo",
                            Nombre = "Joyo",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 30,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 10,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Oaly",
                            Nombre = "Oaly",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 31,
                            AsistenciasTotales = 0,
                            Edad = 25,
                            EquipoId = 11,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Firstkiller",
                            Nombre = "Firstkiller",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 32,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 11,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Lj",
                            Nombre = "Lj",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 33,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 11,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Chronic",
                            Nombre = "Chronic",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 34,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 12,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Fever",
                            Nombre = "Fever",
                            Pais = "OCE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 35,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 12,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Toros",
                            Nombre = "Toros",
                            Pais = "OCE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 36,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 12,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Bananahead",
                            Nombre = "Bananahead",
                            Pais = "OCE",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 37,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 13,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "NIP1",
                            Nombre = "PlayerNIP1",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 38,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 13,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "NIP2",
                            Nombre = "PlayerNIP2",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 39,
                            AsistenciasTotales = 0,
                            Edad = 21,
                            EquipoId = 13,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "NIP3",
                            Nombre = "PlayerNIP3",
                            Pais = "EU",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 40,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 15,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "kv1",
                            Nombre = "kv1",
                            Pais = "SAM",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 41,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 15,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "swiftt",
                            Nombre = "swiftt",
                            Pais = "SAM",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 42,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 15,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "Motta",
                            Nombre = "Motta",
                            Pais = "SAM",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 43,
                            AsistenciasTotales = 0,
                            Edad = 23,
                            EquipoId = 16,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "MaJicBear",
                            Nombre = "MaJicBear",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 44,
                            AsistenciasTotales = 0,
                            Edad = 24,
                            EquipoId = 16,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "CHEESE.",
                            Nombre = "CHEESE.",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        },
                        new
                        {
                            Id = 45,
                            AsistenciasTotales = 0,
                            Edad = 22,
                            EquipoId = 16,
                            GolesTotales = 0,
                            MVPsTotales = 0,
                            Nick = "justin.",
                            Nombre = "justin.",
                            Pais = "NA",
                            PartidosGanados = 0,
                            PartidosJugados = 0,
                            SalvadasTotales = 0
                        });
                });

            modelBuilder.Entity("TournamentManager.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Jugado")
                        .HasColumnType("bit");

                    b.Property<int?>("MVPJugadorId")
                        .HasColumnType("int");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MVPJugadorId");

                    b.HasIndex("RondaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TournamentManager.Models.PartidoJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoPartidoId")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.Property<int>("Salvadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoPartidoId");

                    b.HasIndex("JugadorId");

                    b.ToTable("PartidoJugador");
                });

            modelBuilder.Entity("TournamentManager.Models.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("TournamentManager.Models.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MVPId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonId");

                    b.HasIndex("MVPId");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("TournamentManager.Models.EquipoPartido", b =>
                {
                    b.HasOne("TournamentManager.Models.Equipo", "Equipo")
                        .WithMany("Partidos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentManager.Models.Partido", "Partido")
                        .WithMany("Equipos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("TournamentManager.Models.EquipoTorneo", b =>
                {
                    b.HasOne("TournamentManager.Models.Equipo", "Equipo")
                        .WithMany("Torneos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentManager.Models.Torneo", "Torneo")
                        .WithMany("Equipos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("TournamentManager.Models.Jugador", b =>
                {
                    b.HasOne("TournamentManager.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TournamentManager.Models.Partido", b =>
                {
                    b.HasOne("TournamentManager.Models.Jugador", "MVPJugador")
                        .WithMany()
                        .HasForeignKey("MVPJugadorId");

                    b.HasOne("TournamentManager.Models.Ronda", "Ronda")
                        .WithMany("Partidos")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MVPJugador");

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("TournamentManager.Models.PartidoJugador", b =>
                {
                    b.HasOne("TournamentManager.Models.EquipoPartido", "EquipoPartido")
                        .WithMany("EstadisticasJugadores")
                        .HasForeignKey("EquipoPartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentManager.Models.Jugador", "Jugador")
                        .WithMany("HistorialPartidos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoPartido");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("TournamentManager.Models.Ronda", b =>
                {
                    b.HasOne("TournamentManager.Models.Torneo", "Torneo")
                        .WithMany("Rondas")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("TournamentManager.Models.Torneo", b =>
                {
                    b.HasOne("TournamentManager.Models.Equipo", "Campeon")
                        .WithMany()
                        .HasForeignKey("CampeonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TournamentManager.Models.Jugador", "MVP")
                        .WithMany()
                        .HasForeignKey("MVPId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campeon");

                    b.Navigation("MVP");
                });

            modelBuilder.Entity("TournamentManager.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Partidos");

                    b.Navigation("Torneos");
                });

            modelBuilder.Entity("TournamentManager.Models.EquipoPartido", b =>
                {
                    b.Navigation("EstadisticasJugadores");
                });

            modelBuilder.Entity("TournamentManager.Models.Jugador", b =>
                {
                    b.Navigation("HistorialPartidos");
                });

            modelBuilder.Entity("TournamentManager.Models.Partido", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("TournamentManager.Models.Ronda", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("TournamentManager.Models.Torneo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
